name: Build and Push Docker Images from Monorepo

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del monorepo
      - uses: actions/checkout@v4

      # 2️⃣ Login en GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Install docker-compose
        run: sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      
      - name: Set permissions for docker-compose
        run: sudo chmod +x /usr/local/bin/docker-compose

      #  Build doker-compose
      - name: Build docker-compose
        run: |
          docker-compose build --no-cache
          docker push ghcr.io/stewiemayer/rick-n-morty-mf-app:latest

      # 6️⃣ Trigger deploy en Render
      - name: Deploy to Render
        run: | 
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_RICK_N_MORTY }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
